version: '3'
services:
  postgres:
    container_name: postgresExperience
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=experience
      - POSTGRES_PASSWORD=experience
      - POSTGRES_DB=experience

    #network_mode: host
#  backend:
#    container_name: backend
#    build: ./backend/
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      # Vite takes care of most of this for us, but it's good practice for other backends
#      - VITE_DB_HOST=postgres
#      - VITE_IP_ADDR=0.0.0.0
#      - VITE_PORT=8080
#      - VITE_LOGS_DIR=logs/
#    depends_on: #This is a lie
#      - postgres

  minio:
    container_name: minio
    image: docker.io/bitnami/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_DEFAULT_BUCKETS=doggr:public
      - MINIO_ROOT_USER=minioUser
      - MINIO_ROOT_PASSWORD=minioPass
      - MINIO_SERVER_ACCESS_KEY=minioUser
      - MINIO_SERVER_SECRET_KEY=minioPass
    volumes:
      - minio_data:/data

volumes:
  minio_data:
    driver: local
  db:
    driver: local
